version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - .:/app
    environment:
      - PGHOST=db
      - PGUSER=postgres
      - PGPASSWORD=your_password
      - PGDATABASE=your_database_name
      - PGPORT=5432

  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=your_password
      - POSTGRES_DB=your_database_name
